import type { Metadata } from 'next';
import { Geist, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import AppShell from '@/components/segments/app-shell';

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist',
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${geist.variable} ${jetbrainsMono.variable} h-full antialiased`}>
      <body className="bg-background flex min-h-full flex-col text-neutral-50">
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
